from pydantic import BaseModel, EmailStr
from typing import Optional


# ✅ Schema for Vendor Creation
class VendorCreate(BaseModel):
    name: str
    email: EmailStr
    phone: str


# ✅ Schema for User Signup (Updated & Fixed)
class UserCreate(BaseModel):
    name: str
    email: EmailStr  # ✅ Ensures valid email format
    po_wo_so_number: str
    site_name: str
    company_name: str
    mobile_number: str
    password: str

    class Config:
        from_attributes = True  # ✅ Fix for Pydantic v2 (Replaces orm_mode)


# ✅ Schema for Returning User Data (Fix `orm_mode` for Pydantic v2)
class UserResponse(BaseModel):
    id: int
    name: str
    email: EmailStr  # ✅ Ensure email is valid
    po_wo_so_number: str
    site_name: str
    company_name: str
    mobile_number: str

    class Config:
        from_attributes = True  # ✅ Fixes compatibility with FastAPI & Pydantic v2

# Base Employee Schema
class EmployeeBase(BaseModel):
    name: str
    designation: str
    email: str
    phone: str
    company: str

# Schema for Creating an Employee
class EmployeeCreate(EmployeeBase):
    pass  # No additional fields required for now

# Schema for Reading an Employee (includes ID)
class Employee(EmployeeBase):
    id: int

    class Config:
        from_attributes = True  # Corrected for Pydantic V2
        
class Employee(BaseModel):
    id: Optional[int] = None  # Optional ID, usually auto-generated by the database
    name: str
    designation: str
    email: str
    phone: str
    company: str

    class Config:
        orm_mode = True  # Allows SQLAlchemy models to be converted into Pydantic models