"""Added PF and ESIC Contribution columns

Revision ID: 174fd5d0cdc9
Revises: 4798d4ea0675
Create Date: 2025-03-22 20:34:57.733153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174fd5d0cdc9'
down_revision: Union[str, None] = '4798d4ea0675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('uan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('esic_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('working_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('basic_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('hra', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pf_contribution', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('esic_contribution', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('gross_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('deductions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ot', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('advance_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bank_transfer_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bonus_detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bonus_paid_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('leave_record', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('leave_encashment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fine_detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('damage_loss_detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('other_allowance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pf_wages', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employee_records_pkey')
    )
    # ### end Alembic commands ###
