"""Added EmployeeRecord model

Revision ID: b297b4f619fc
Revises: 1d450488ed2d
Create Date: 2025-03-27 17:51:49.253882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b297b4f619fc'
down_revision: Union[str, None] = '1d450488ed2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_audits_id', table_name='audits')
    op.drop_table('audits')
    op.drop_index('ix_employee_records_id', table_name='employee_records')
    op.drop_table('employee_records')
    op.drop_index('ix_observations_id', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_vendors_id', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('po_wo_so_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('vendor', 'client', 'internal', name='user_roles'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vendors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vendors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vendors_id', 'vendors', ['id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], name='observations_audit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='observations_pkey')
    )
    op.create_index('ix_observations_id', 'observations', ['id'], unique=False)
    op.create_table('employee_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('uan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('esic_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('working_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('basic_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('hra', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('any_other_allowance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pf_contribution', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('esic_contribution', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('gross', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('deductions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ot', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('advance_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bank_transfer_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bonus_detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bonus_paid_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('leave_record', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('leave_encashment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fine_detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('damage_loss_detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pf_wages', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_salary', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employee_records_pkey')
    )
    op.create_index('ix_employee_records_id', 'employee_records', ['id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('audit_month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uploaded_documents', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audits_pkey')
    )
    op.create_index('ix_audits_id', 'audits', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='documents_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    op.create_index('ix_documents_id', 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
